name: 'Initialize integ-test'

runs:
  using: "composite"
  steps: 
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11

    # Downloads a 'dist' directory artifact that was uploaded in an earlier step
    # We control this with an environment variable to allow for easier global configuration.
    - name: Download dist
      if: ${{ env.DOWNLOAD_DIST == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
