name: Test dependency-submission submit

on:
  workflow_run:
    workflows: ['Test dependency-submission save']
    types: [completed]

permissions:
  contents: write

jobs:
  dependency-submission-submit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Download and submit dependency graph
      uses: ./dependency-submission
      with:
        dependency-graph: download-and-submit
